[config]
schemaVersion = "0.0.1"

[package]
namespace = "Mythic"
name = "ServerLaunchFix"
versionNumber = "0.2.0"
description = "Enable mods for single player and host & play"
websiteUrl = "https://github.com/MythicManiac/VRising"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]
categories = []
